#!/usr/bin/env python3
"""Build docs/design/v4_implementation_matrix.md from the authored tree and the
hand-maintained status file tools/design/v4_status.json.

Status per node: implemented | partial | missing | ambiguous | n/a. The
generator also greps the runtime for each node id, so a node marked
implemented that no engine references is flagged, and vice versa.

Run:  python3 tools/design/build_v4_matrix.py
"""
import json, re, glob, collections, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TREE = os.path.join(ROOT, "data/ascension/tree_v4.json")
STATUS = os.path.join(ROOT, "tools/design/v4_status.json")
OUT = os.path.join(ROOT, "docs/design/v4_implementation_matrix.md")
CODE_GLOBS = ["core/systems/ascension/**/*.gd", "autoload/global.gd", "autoload/DevSetCollisionTools.gd", "ui/screens/Ascension*.gd"]

tree = json.load(open(TREE))
status = json.load(open(STATUS))
nodes = tree["nodes"]
src = ""
for pattern in CODE_GLOBS:
    for f in glob.glob(os.path.join(ROOT, pattern), recursive=True):
        src += open(f).read()

def referenced(node_id):
    return re.search(r'["\']%s["\']' % re.escape(node_id), src) is not None

discipline_name = {d["code"]: d["name"] for d in tree["disciplines"]}
order = ["EX", "MO", "BA", "PR", "BR", "OR", "IN", "DT", "DO"]
groups = collections.OrderedDict()
for code in order:
    groups[code] = []
for n in nodes:
    key = n["discipline"] or n["kind"]
    groups.setdefault(key, []).append(n)

counts = collections.Counter()
flags = []
lines = ["# V4 implementation matrix", "",
         "Generated by `tools/design/build_v4_matrix.py` from `data/ascension/tree_v4.json` and",
         "`tools/design/v4_status.json`. Edit the status file, not this page.", "",
         "Status: **implemented** (authored rule runs, verified by the named test),",
         "**partial** (runs with a documented approximation or a missing clause),",
         "**missing** (purchasable, no effect), **ambiguous** (rule needs a decision),",
         "**n/a** (progression-only node whose rule lives in the ledger).", ""]

summary_rows = []
for key, group in groups.items():
    if not group:
        continue
    title = discipline_name.get(key, key.capitalize())
    c = collections.Counter(status.get(n["id"], {}).get("status", "missing") for n in group)
    summary_rows.append((title, key, len(group), c))
lines.append("## Summary")
lines.append("")
lines.append("| Group | Nodes | Implemented | Partial | Missing | Ambiguous | n/a |")
lines.append("|---|---:|---:|---:|---:|---:|---:|")
for title, key, total, c in summary_rows:
    lines.append("| %s (%s) | %d | %d | %d | %d | %d | %d |" % (title, key, total, c["implemented"], c["partial"], c["missing"], c["ambiguous"], c["n/a"]))
    counts.update(c)
lines.append("| **All** | %d | %d | %d | %d | %d | %d |" % (len(nodes), counts["implemented"], counts["partial"], counts["missing"], counts["ambiguous"], counts["n/a"]))
lines.append("")

shared = status.get("_shared", {})
if shared:
    lines.append("## Shared rules")
    lines.append("")
    lines.append("| Rule | Status | Where | Verified by | Note |")
    lines.append("|---|---|---|---|---|")
    for name, entry in shared.items():
        lines.append("| %s | %s | %s | %s | %s |" % (name, entry.get("status", "missing"), entry.get("where", ""), entry.get("test", ""), entry.get("note", "")))
    lines.append("")

for key, group in groups.items():
    if not group:
        continue
    title = discipline_name.get(key, key.capitalize())
    lines.append("## %s (%s)" % (title, key))
    lines.append("")
    lines.append("| Id | Name | Kind | Ring | Status | Where | Verified by | Note |")
    lines.append("|---|---|---|---:|---|---|---|---|")
    for n in sorted(group, key=lambda x: (x["ring"], x["id"])):
        entry = status.get(n["id"], {})
        st = entry.get("status", "missing")
        ref = referenced(n["id"])
        note = entry.get("note", "")
        if st in ("implemented", "partial") and not ref:
            note = (note + " " if note else "") + "**[no code reference]**"
            flags.append("%s marked %s but no runtime references it" % (n["id"], st))
        if st == "missing" and ref and n["kind"] not in ("core", "gate", "choice"):
            note = (note + " " if note else "") + "_(referenced in code)_"
        lines.append("| %s | %s | %s | %d | %s | %s | %s | %s |" % (n["id"], n["name"], n["kind"], n["ring"], st, entry.get("where", ""), entry.get("test", ""), note))
    lines.append("")

if flags:
    lines.append("## Consistency flags")
    lines.append("")
    for f in flags:
        lines.append("- " + f)
    lines.append("")

open(OUT, "w").write("\n".join(lines))
print("wrote", os.path.relpath(OUT, ROOT), "|", dict(counts), "| flags:", len(flags))
